name: plantapp
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=3.3.0-279.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_svg:

  #screen
  flutter_screenutil: ^5.9.0

  

  #dateFormat
  intl: any

  #Font Family
  google_fonts: ^6.1.0

  #service locator
  get: ^4.6.6

  #chached image
  flutter_riverpod: ^2.4.9

  # Fetch Data From Api
  dio: ^5.4.0

  # Being able to compare objects in Dart
  equatable: ^2.0.5

  #make request to api
  retrofit: ^4.0.3

  #Database
  # floor: ^1.4.2

  # BloC State Management
  flutter_bloc: ^8.1.3

  shared_preferences: ^2.2.2
  get_storage: ^2.1.1
  flutter_hooks: ^0.20.4
  cached_network_image: ^3.3.1

  image_picker: ^1.0.5
  permission_handler: ^11.3.0
  camera: ^0.10.5+9
  share_plus: ^7.2.2

  flutter_background_service: ^5.0.5
  # awesome_notifications: ^0.8.2
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  http: ^1.2.0
  latlong2: ^0.9.0
  sliding_up_panel: ^2.0.0+1
  # geolocator: ^11.0.0

  flutter_phone_direct_caller: ^2.1.1

  multi_image_picker_view: ^0.0.17
  abushakir: ^1.0.0

  rflutter_alert: ^2.0.7
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.5
  hexagon: ^0.2.0
  connectivity: ^3.0.6
  # firebase_core: ^2.27.0
  # firebase_auth: ^4.17.8
  pin_code_fields: ^8.0.1
  flutter_local_notifications:
  # auto_start_flutter: ^0.1.1
  device_info_plus: ^9.1.2
  sms_autofill: ^2.3.1
  alt_sms_autofill: ^1.0.0
  flutter_localizations:
    sdk: flutter
  sms_receiver: ^0.4.2
  data_table_2: ^2.4.2
  excel: ^4.0.3
  file_picker: ^5.5.0
  change_app_package_name: ^1.1.0
  pie_chart: ^5.4.0
  ethiopiandatepickerandconvertor: ^0.0.6
  # curved_labeled_navigation_bar: ^2.0.2

  # flutter_background_service_android: ^6.2.2
  # flutter_background_service_ios: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.0.6
  floor_generator: ^1.4.2
  build_runner: ^2.4.8
  flutter_circular_text: ^0.3.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_lancher.png" # Path to your custom icon file

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    # - assets/menus/
    # - assets/features/
  # fonts:
  #   - family: AbyssinicaSIL
  #     fonts:
  #       - asset: assets/fonts/AbyssinicaSIL-Regular.ttf
  #   - family: Amharic
  #     fonts:
  #       - asset: assets/fonts/NotoSerifEthiopic-VariableFont_wdth.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
